// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6W_YvwiyuSPr_5HkpcNOZv_3ohpKAwUI',
    appId: '1:41206483940:web:cdd471c5eac8ad33f955f1',
    messagingSenderId: '41206483940',
    projectId: 'garbagemap-5a1e8',
    authDomain: 'garbagemap-5a1e8.firebaseapp.com',
    storageBucket: 'garbagemap-5a1e8.appspot.com',
    measurementId: 'G-R7T43KFXXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0I1Bp9TGZFkPUJ7-b4YWa72v1zaOWLAU',
    appId: '1:41206483940:android:5ee7808d85dfb371f955f1',
    messagingSenderId: '41206483940',
    projectId: 'garbagemap-5a1e8',
    storageBucket: 'garbagemap-5a1e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-WDpN4AdrfFu38MC2WGsjMESQBUvyBnU',
    appId: '1:41206483940:ios:0e7292753fbe2f1cf955f1',
    messagingSenderId: '41206483940',
    projectId: 'garbagemap-5a1e8',
    storageBucket: 'garbagemap-5a1e8.appspot.com',
    androidClientId: '41206483940-0jmc2kakeqr3h4uic65a9aonklv8qcbn.apps.googleusercontent.com',
    iosClientId: '41206483940-vedm3grk9gbrigts7v1s8ppugbojuq7b.apps.googleusercontent.com',
    iosBundleId: 'com.garbage.mapper.forestGarbageMapper',
  );
}
