name: Github Actions CI Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  JAVA_VERSION: 17
  FLUTTER_VERSION: '3.3.0'
  FLUTTER_CHANNEL: stable
jobs:
  flutter_test:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: adopt
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{env.FLUTTER_CHANNEL}}
          flutter-version: ${{env.FLUTTER_VERSION}}
      - run: |
          flutter clean
          flutter pub get
          flutter analyze
          flutter format lib/
  build_web:
    name: Build for WEB
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{env.FLUTTER_CHANNEL}}
          flutter-version: ${{env.FLUTTER_VERSION}}
      - run: |
          flutter clean
          flutter upgrade --major-versions
          flutter pub get
          flutter build web
  build_android:
    name: Build Flutter (Android)
    needs: [build_web]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: 'adopt'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          channel: ${{env.FLUTTER_CHANNEL}}
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk
      - name: Upload app release
        uses: actions/upload-artifact@v3
        with:
          name: garbage-mapper release
          path: build/app/outputs/flutter-apk/app-release.apk
  publish_ghPages:
    name: Publish GH Pages
    needs: [build_web]
    env:
      my_secret: ${{secrets.COMMIT_SECRET}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{env.FLUTTER_CHANNEL}}
      - run: |
          flutter clean
          flutter pub get
          flutter build web --release
          cd build/web
          git init
          git config --global user.email shepard128@gmail.com
          git config --global user.name ChrisRPL
          git status
          git remote add origin https://${{secrets.COMMIT_SECRET}}@github.com/ChrisRPL/ForestGarbageMapper.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
